# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "usbhid"
    "uas"
    "sd_mod"
    "rtsx_usb_sdmmc"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/88d6dcb3-b98f-4e18-bc2a-7dafbc17a75a";
    fsType = "btrfs";
    options = [
      "subvol=@nix-root"
      "discard=async"
      "compress=zstd"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/1484-193D";
    fsType = "vfat";
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/88d6dcb3-b98f-4e18-bc2a-7dafbc17a75a";
    fsType = "btrfs";
    options = [
      "subvol=@home"
      "discard=async"
      "compress=zstd"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/88d6dcb3-b98f-4e18-bc2a-7dafbc17a75a";
    fsType = "btrfs";
    options = [
      "subvol=@nix"
      "discard=async"
      "compress=zstd"
    ];
  };

  fileSystems."/mnt/arch" = {
    device = "/dev/disk/by-uuid/d0610b47-9585-4d8a-906a-8c368652c9dd";
    fsType = "btrfs";
    options = [
      "subvol=@"
      "discard=async"
      "compress=zstd"
    ];
  };

  fileSystems."/mnt/arch/home" = {
    device = "/dev/disk/by-uuid/d0610b47-9585-4d8a-906a-8c368652c9dd";
    fsType = "btrfs";
    options = [
      "subvol=@home"
      "discard=async"
      "compress=zstd"
    ];
  };
  fileSystems."/mnt/data" = {
    device = "/dev/disk/by-uuid/88d6dcb3-b98f-4e18-bc2a-7dafbc17a75a";
    fsType = "btrfs";
    options = [
      "subvol=@data"
      "discard=async"
    ];
  };

  swapDevices = [ { device = "/dev/disk/by-uuid/483bf3f2-8dfb-4ea7-a207-404a11b9e8c9"; } ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
